### PR TITLE
Fix login url so it won't show on the url line

### PR DESCRIPTION
**Pull request by Avielyo10**

### CODE REVIEW

**Comment by Avielyo10** [comment]
This should be a fix for this issue https://github.com/reportportal/service-authorization/issues/86

**Comment by AmsterGet** [comment]
For the `4`th version it's also already fixed [here](https://github.com/reportportal/service-ui/pull/1814)

**Comment by Avielyo10** [comment]
As you can see [here](https://github.com/reportportal/service-authorization/issues/86#issuecomment-531932745) that's not fixed.

**Comment by AmsterGet** [comment]
Already fixed in the [`v4`](https://github.com/reportportal/service-ui/tree/v4) branch, but it is still not released.
A release for `v4` will be available when QA team finish the regression tests for` v5-beta`.

**Comment by Avielyo10** [comment]
@AmsterGet Thanks that's great!
Do you have any time estimation?

**Comment by englandprevails** [comment]
There is no public release with this security flaw fixed.  Why is this issue closed?

**Pull request closed without merging**
