### PR TITLE
EPMRPP-87330 || Service-ui Security vulnerabilities

### PR DESCRIPTION
**Pull request by BlazarQSO**

### CODE REVIEW

**Review by AmsterGet — CHANGES_REQUESTED** [review]
Please also check is it possible to bump `c3` lib version, because vulnerable `d3-color` is a sub dependency of it.

image

**Comment by AmsterGet** [comment]
Also check the `semver` package as its vulnerable versions are not fully updated within this PR.

**Comment by Bam6ycha** [comment]
> Please also check is it possible to bump `c3` lib version, because vulnerable `d3-color` is a sub dependency of it.
> 
> image

The latest version of c3 depends on c3 v 1.4.1
So, we can not fix this vulnerability

**Comment by Bam6ycha** [comment]
Screenshot 2023-11-14 at 13 42 16

**Comment by AmsterGet** [comment]
Closed in favor of https://github.com/reportportal/service-ui/pull/3655

**Pull request closed without merging**
