### PR TITLE
Fix login username and password double encoded

### PR DESCRIPTION
**Pull request by waynesun09**
With data as object and add contentType, the password was double
encoded and login will fail with special charcater like '@'.

To fix the username and password value, decode it before pass to
ajax.

Signed-off-by: Wayne Sun <gsun@redhat.com>

### CODE REVIEW

**Comment by AmsterGet** [comment]
We have restrictions for the login field (Latin, numeric characters, hyphen, underscore, period), so the `@` character is not allowed.

Сan it be delayed?
At the moment, all our forces are focused on version 5.

**Comment by waynesun09** [comment]
@AmsterGet For the v4, I tested with '@' and it works, this happened after the fix
https://github.com/reportportal/service-ui/commit/fd0cf0542e0ad736c77859fc13f7a13e6b48460e

So current official release is not affected.
For authorization with LDAP, strong password is preferred and special characters should not be excluded. 

As it not affect the release version, I think it could be delayed until next v4 release.

**Comment by AmsterGet** [comment]
Thanks for the quick response.

Added in the scope of version 4.4.

**Comment by AmsterGet** [comment]
Closed as v4 is out of support.

**Pull request closed without merging**
