### PR TITLE
add Simplified Chinese(2% translated, Need Help.)

### PR DESCRIPTION
**Pull request by kisscelia**
developed on develop branch.

### CODE REVIEW

**Comment by kisscelia** [comment]
Hi, @AmsterGet

I am so sorry, I close the #3177  and I made a new PR( developed on branch(develop))

Can you review this PR?

Thank you very much.

**Comment by AmsterGet** [comment]
@kisscelia Hello!
I see several linter errors at [CI pipeline](https://github.com/reportportal/service-ui/runs/7783496158?check_suite_focus=true).
Could you please fix them?

**Comment by kisscelia** [comment]
> @kisscelia Hello! I see several linter errors at [CI pipeline](https://github.com/reportportal/service-ui/runs/7783496158?check_suite_focus=true). Could you please fix them?

Hi, @AmsterGet 
Thanks for your reply.

Bug Fixed. pls check again, thanks.

**Review by AmsterGet — APPROVED** [review]

**Comment by AmsterGet** [comment]
Thank you @kisscelia !

**Comment by kisscelia** [comment]
> Thank you @kisscelia !

: - )

**Pull request merged**
