### PR TITLE
EPMRPP-78764 || Defect types system messages depending on length

### PR DESCRIPTION
**Pull request by tr1ble**
EPMRPP-78764 || Defect types system messages depending on length, color picker pointer style fix

### CODE REVIEW

**Comment by Vadim73i** [comment]
1) If user can't create a new defect because of limits, "Create a new Defect" icons should be disabled, not hidden. Tooltip remains.
https://www.figma.com/file/7Y3Sr3bwJ281dXoRi0Liue/%E2%9A%99%EF%B8%8F-RP6-Project-level?node-id=8087%3A197549

2) If only 1 slot is available, the text should be "1 slot left" instead of "1 slots left"

**Comment by tr1ble** [comment]
> 1. If user can't create a new defect because of limits, "Create a new Defect" icons should be disabled, not hidden. Tooltip remains.
>    https://www.figma.com/file/7Y3Sr3bwJ281dXoRi0Liue/%E2%9A%99%EF%B8%8F-RP6-Project-level?node-id=8087%3A197549
> 2. If only 1 slot is available, the text should be "1 slot left" instead of "1 slots left"



> 1. If user can't create a new defect because of limits, "Create a new Defect" icons should be disabled, not hidden. Tooltip remains.
>    https://www.figma.com/file/7Y3Sr3bwJ281dXoRi0Liue/%E2%9A%99%EF%B8%8F-RP6-Project-level?node-id=8087%3A197549
> 2. If only 1 slot is available, the text should be "1 slot left" instead of "1 slots left"

1, To be honest, I didn't see it on my screen because of brigthness :(

**Comment by tr1ble** [comment]
> 1. If user can't create a new defect because of limits, "Create a new Defect" icons should be disabled, not hidden. Tooltip remains.
>    https://www.figma.com/file/7Y3Sr3bwJ281dXoRi0Liue/%E2%9A%99%EF%B8%8F-RP6-Project-level?node-id=8087%3A197549
> 2. If only 1 slot is available, the text should be "1 slot left" instead of "1 slots left"

Fixed both, thanks

**Review by Vadim73i — APPROVED** [review]

**Review by chivekrodis — COMMENTED** [review]
Please make sure that's expected result for donut on the launch view
image

Also recheck all widgets as I see old TI color at least on the 'Investigated percentage of launches' widget

**Comment by tr1ble** [comment]
> Please make sure that's expected result for donut on the launch view image
> 
> Also recheck all widgets as I see old TI color at least on the 'Investigated percentage of launches' widget

1. Yes, as I checked it's OK
2. As I checked, everything is fine
image

**Comment by chivekrodis** [comment]
> > Please make sure that's expected result for donut on the launch view image
> > Also recheck all widgets as I see old TI color at least on the 'Investigated percentage of launches' widget
> 
> 1. Yes, as I checked it's OK. For now we don't have updated design for this place
> 2. As I checked, everything is fine
>    image

image

**Comment by tr1ble** [comment]
> > > Please make sure that's expected result for donut on the launch view image
> > > Also recheck all widgets as I see old TI color at least on the 'Investigated percentage of launches' widget
> > 
> > 
> > 
> > 1. Yes, as I checked it's OK. For now we don't have updated design for this place
> > 2. As I checked, everything is fine
> >    image
> 
> image

Thanks, fixed

**Review by chivekrodis — APPROVED** [review]

**Pull request merged**
